apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: blog
type: Opaque
stringData:
  mysql-root-password: "blogB022."
  mysql-password: "blogB022."
  redis-password: "blogB022."
  jwt-secret: "blog-jwt-secret-key-2026"
